"""
instance_ensemble.py — where do our two hardware-measured reservoir instances sit in the
*distribution* of instances?

Motivation. The S7 cross-seed control (results/qpu_hardware_findings.md §S7) measured two n=8
instances on the same chip in the same session: seed-0 scrambled (raw 0.2284), seed-1 was
signal-bearing (raw 0.1594). That is a hardware n=2. A fair reviewer asks: are those two draws
typical, or did we happen to compare an unusually easy instance against an unusually hard one?

This script answers that with *exact*, offline computation over 30 seeded instances — no
hardware, no shots, no sampling. For each instance it computes:
  * the number of two-qubit couplings (edges of the random J graph) — the entangling-gate cost
    the circuit pays per Trotter layer;
  * the fully-depolarized limit mean|F_exact| — the instance's own signal-bearing bar.

SCOPE (stated plainly). This characterizes the *instance ensemble* and locates our two
hardware-measured instances inside it. It does NOT add hardware instances: the on-metal
evidence at n=8 remains those two campaigns. What it rules out is the possibility that the S7
contrast was an artifact of comparing a cheap circuit against an expensive one.

Regenerate: python3 instance_ensemble.py   (or: python3 cli.py run instance_ensemble)
"""
import json
import numpy as np

from qrc_engine import generate_coupling_matrix
from qbraid_submit import engine_features, real_rv_windows

N, CONN, K_WINDOWS, N_SEEDS = 8, 0.5, 3, 30      # matches the hardware protocol config
MEASURED = {0: ("seed-0", 0.2284, "scrambled"), 1: ("seed-1", 0.1594, "signal-bearing")}


def build():
    wins = real_rv_windows(N, k=K_WINDOWS)
    rows = []
    for seed in range(N_SEEDS):
        J = generate_coupling_matrix(N, CONN, seed=seed)
        edges = int(np.count_nonzero(np.triu(J, 1)))
        F = np.array([engine_features(N, seed)(w) for w in wins])
        rows.append({"seed": seed, "edges": edges, "limit": float(np.abs(F).mean())})
    return rows


def main():
    rows = build()
    edges = np.array([r["edges"] for r in rows], dtype=float)
    lims = np.array([r["limit"] for r in rows], dtype=float)
    corr = float(np.corrcoef(edges, lims)[0, 1])

    print(f"n={N}, {N_SEEDS} instances (seeds 0-{N_SEEDS-1}), connectivity={CONN}, "
          f"{K_WINDOWS} RV windows — exact, no hardware")
    print(f"  two-qubit edges     min {edges.min():.0f}  median {np.median(edges):.0f}  max {edges.max():.0f}")
    print(f"  limit mean|F_exact| min {lims.min():.4f}  median {np.median(lims):.4f}  max {lims.max():.4f}")
    print(f"  corr(edges, limit) = {corr:+.3f}   (denser instances face a TIGHTER bar)\n")

    lines = []
    for seed, (lab, raw, regime) in MEASURED.items():
        r = rows[seed]
        pe = float((edges < r["edges"]).sum()) / len(edges) * 100
        pl = float((lims < r["limit"]).sum()) / len(lims) * 100
        print(f"  {lab} (measured on Garnet: raw {raw:.4f}, {regime:<14}) "
              f"edges {r['edges']:2d} = {pe:3.0f}th pctile   limit {r['limit']:.4f} = {pl:3.0f}th pctile")
        lines.append((lab, raw, regime, r["edges"], pe, r["limit"], pl))

    e0, e1 = rows[0]["edges"], rows[1]["edges"]
    print(f"\n  VERDICT: the instance that SCRAMBLED (seed-0) carries {e0} two-qubit couplings; the one "
          f"that stayed\n  signal-bearing (seed-1) carries {e1}. Entangling-gate count does not explain "
          f"the wall —\n  on these two measured instances it anti-predicts it.")

    with open("results/instance_ensemble_findings.md", "w", encoding="utf-8") as fh:
        fh.write(f"""# Instance ensemble — where our two measured n=8 instances sit

*Generated by `instance_ensemble.py` (`python3 cli.py run instance_ensemble`). Exact computation
over {N_SEEDS} seeded reservoir instances at n={N}, connectivity={CONN}, {K_WINDOWS} RV windows.
**No hardware, no shots, no sampling** — every number below is deterministic and re-derivable.*

## Why this exists

S7 (`qpu_hardware_findings.md` §S7) compared two n={N} instances on the same chip in the same
session: **seed-0 scrambled** (raw 0.2284) while **seed-1 was signal-bearing** (raw 0.1594). That
is a hardware n=2. The fair objection is: *were those two typical draws, or did you compare an
unusually cheap circuit against an unusually expensive one?* This file answers it.

## The ensemble

| quantity | min | median | max |
|---|---|---|---|
| two-qubit couplings (edges of J) | {edges.min():.0f} | {np.median(edges):.0f} | {edges.max():.0f} |
| depolarized limit mean\\|F_exact\\| | {lims.min():.4f} | {np.median(lims):.4f} | {lims.max():.4f} |

`corr(edges, limit) = {corr:+.3f}` — denser instances face a **tighter** signal-bearing bar.

## Where the two measured instances sit

| instance | measured raw (Garnet) | regime on metal | 2Q edges | edge pctile | own limit | limit pctile |
|---|---|---|---|---|---|---|
""")
        for lab, raw, regime, ed, pe, lim, pl in lines:
            fh.write(f"| **{lab}** | {raw:.4f} | {regime} | {ed} | {pe:.0f}th | {lim:.4f} | {pl:.0f}th |\n")
        fh.write(f"""
## What this establishes

1. **The S7 contrast is not a cheap-vs-expensive artifact — it runs the other way.** The instance
   that **scrambled** (seed-0, {e0} couplings) is among the **sparsest** in the ensemble; the one that
   stayed **signal-bearing** (seed-1, {e1} couplings) is among the **densest**. Seed-1 also faced the
   **tighter** bar ({rows[1]['limit']:.4f} vs {rows[0]['limit']:.4f}) and cleared it anyway. Seed-1 passed a harder
   test on **both** axes.
2. **Accumulated two-qubit-gate count does not explain the coherence-budget wall.** On the two
   instances we measured on metal it *anti-predicts* the outcome. This is the quantitative form of
   the paper's claim that spec-sheet/gate-count reasoning fails for per-workload QPU qualification.
3. **The depolarized limit is instance-dependent** (range {lims.min():.4f}–{lims.max():.4f} at fixed n={N}),
   which is why comparators are keyed by `(n, seed)` in `score_campaign.py`
   (`DEPOLARIZED_LIMITS_BY_INSTANCE`) — see the self-correction note in §S7.

## Limits of this analysis (stated plainly)

- This is an **ensemble characterization**, not additional hardware. The on-metal evidence at n=8
  remains the **two** S7 instances plus the earlier seed-0 campaigns. We do **not** claim 30
  measured instances, and we do **not** claim to have identified the mechanism.
- It rules out one specific confound (entangling-gate cost) and locates our draws in the
  distribution. What actually causes the seed-0 instance to scramble — coupling geometry, lattice
  embedding, or a per-feature sensitivity — remains **open**; the embedding arm (**H-EMBED**) is
  pre-registered and unrun (`qpu_scaling_outlook.md`).
""")
    json.dump(rows, open("results/instance_ensemble.json", "w"), indent=1)
    print("\nsaved results/instance_ensemble_findings.md + results/instance_ensemble.json")


if __name__ == "__main__":
    main()
